# TravisCI config file. See http://travis-ci.org
language: python

python:
  - 2.7

env:
  global:
    # global environment variables
    - MYSQL_TEST_HOST=127.0.0.1
    - MYSQL_TEST_USER=travis MYSQL_TEST_PASSWORD=''
    - MYSQL_TEST_DB=b3_test
    - POSTGRESQL_TEST_HOST=127.0.0.1
    - POSTGRESQL_TEST_USER=postgres
    - POSTGRESQL_TEST_PASSWORD=''
    - POSTGRESQL_TEST_DB=b3_test

cache:
  # cache PIP install across jobs
  - pip

addons:
  # select postgresql version
  postgresql: "9.3"

before_install:
  # install build requirements according to the running os
  - ./scripts/install-build-deps-linux.sh

install:
  # install PIP requirements
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r build-requirements.txt
  - pip install -r optional-requirements.txt
  - pip install -r test-requirements.txt

before_script:
  # create postgresql database
  - psql -c "CREATE DATABASE b3_test WITH OWNER = postgres ENCODING = 'UTF8';" -U postgres

script:
  - nosetests --where=tests --verbosity=3 --with-cov --cov b3 --cov-report term-missing --cov-config .coveragerc --exclude-dir-file=tests/exclude_dir.txt --exclude-test-file=tests/exclude_test.txt
  - nosetests --where=tests.plugins.poweradminbf3 --verbosity=3 --with-cov --cov b3.plugins.poweradminbf3 --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.poweradminurt --verbosity=3 --with-cov --cov b3.plugins.poweradminurt --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.urtserversidedemo --verbosity=3 --with-cov --cov b3.plugins.urtserversidedemo --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.test_callvote --verbosity=3 --with-cov --cov b3.plugins.callvote --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.test_firstkill --verbosity=3 --with-cov --cov b3.plugins.firstkill --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.test_jumper --verbosity=3 --with-cov --cov b3.plugins.jumper --cov-report term-missing --cov-config .coveragerc
  - nosetests --where=tests.plugins.test_spawnkill --verbosity=3 --with-cov --cov b3.plugins.spawnkill --cov-report term-missing --cov-config .coveragerc
  - py.test tests/plugins/makeroom
  - py.test tests/plugins/afk
  - python setup.py egg_info --tag-build .dev${TRAVIS_COMMIT:0:7} --tag-date sdist bdist_wheel
  - python setup.py build_exe

after_success:
  - pip install coveralls
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/489374443a557d989111
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: never